# Generated by Django 3.2.25 on 2025-05-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0002_alter_picture_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
